#!c:\users\yall\github\azclidev\tenv\scripts\python.exe
# EASY-INSTALL-DEV-SCRIPT: 'azure-cli==2.3.1','az'
__requires__ = 'azure-cli==2.3.1'
__import__('pkg_resources').require('azure-cli==2.3.1')
__file__ = 'C:\\Users\\yall\\github\\azure-cli\\src\\azure-cli\\az'
with open(__file__) as f:
    exec(compile(f.read(), __file__, 'exec'))
